### ISSUE TITLE
Unable to solve simple 3-link planar arm

### ISSUE THREAD

**Issue by drfastolfe** [uw-biorobotics/IKBT#12]
I wanted to test the solver so I entered a basic 3-link planar arm as a custom robot:
`
        
    if(name == 'Arm_3'):                
        #
        
        dh = sp.Matrix([
        [ 0 , a_1 , 0 , th_1 ],
        [ 0 , a_2 , 0 , th_2 ],
        [ 0 , a_3 , 0 , th_3 ],
        [ 0 , 0 , 0 , 0 ],
        [ 0 , 0 , 0 , 0 ],
        [ 0 , 0 , 0 , 0 ]
        ])

        vv = [1,1,1,0,0,0]
        variables =  [unknown(th_1), unknown(th_2), unknown(th_3)]
        params = [a_1, a_2, a_3]
        pvals = {a_1:1, a_2:1, a_3:1}
`

ikSolver is unable to solve for this arm. It solves for th_1 and th_2 and then gets stuck while solving for th_3. I get no error message, nothing, the terminal is just stuck. This is the output:
```

     Running IK solution




             Working on Arm_3


kinematics pickle: trying to open  fk_eqns/Arm_3_pickle.p  in  /home/drfastolfe/IKBT
Did not find VALID stored pickle file:  fk_eqns/Arm_3_pickle.p
Starting Forward Kinematics
Completed Forward Kinematics
Starting Sum of Angles scan (slow!)
ik_classes: length Robot.mequation_list:  8
Starting sum-of-angles scan. Please be patient
 [  1%] [................................................] Sum of Anglesfound new 'joint' (sumofangle) variable: (k= 0 )  th_123
sumofanglesT: appending new equation: th_123 = th_1 + th_2 + th_3
 [  4%] [==..............................................] Sum of Anglesfound new 'joint' (sumofangle) variable: (k= 0 )  th_12
sumofanglesT: appending new equation: th_12 = th_1 + th_2
 [ 13%] [======..........................................] Sum of Anglesfound new 'joint' (sumofangle) variable: (k= 1 )  th_23
sumofanglesT: appending new equation: th_23 = th_2 + th_3
 [100%] [================================================] Sum of Angles
Completed sum-of-angles scan.
[th_1, th_2, th_3, th_123, th_12, th_23]
[th_1, th_2, th_3, th_123, th_12, th_23]
 Storing kinematics pickle for Arm_3(fk_eqns/Arm_3_pickle.p)
GOT HERE: robot name:  Arm_3
Ticking IK BT for  Arm_3  -------------------------


variable on blackboard: th_1
basenode:  TanID+Solv  ticked
tan_id: ( th_1 )   0 =  Aw*sin(th)+Bw , 0 = Cw*cos(th) + Dw
Aw:  a_2    Bw:  -Py + a_3*sin(th_1 + th_2)
Cw:  a_2    Dw:  -Px + a_1 + a_3*cos(th_12)
basenode:  TanID+Solv  FAIL
Simultaneous Eqn Unsuccessful: divded by 0
Looking for unknown:  th_1  in equation:  r_11 = cos(th_123)
Looking for unknown:  th_1  in equation:  r_13*cos(th_1) + r_23*sin(th_1) = 0



set_solved:  th_1       by:  sinANDcos
             th_1 = atan2(r_13, -r_23)


 -  - - - -
[th_1, th_2, th_3, th_123, th_12, th_23]
Trying to find:  th_1
 - - - - -
atan2(r_13, -r_23)
//////////////////////// > 1 sol
curr:  th_1s1
a*b
//////////////////////// > 1 sol
curr:  th_1s2
a*b
finish set_solved th_1
basenode:  Completion Detect  ticked





           Completion Detector:  6  variables,  1  are solved.
             solved:  th_1 (sinANDcos);



basenode:  Completion Detect  FAIL
variable on blackboard: th_2



set_solved:  th_2       by:  algebra
             th_2 = zoo*(Py - a_2*sin(th_1) - a_3*sin(th_1 + th_2))


 -  - - - -
[th_1, th_2, th_3, th_123, th_12, th_23]
Trying to find:  th_2
 - - - - -
zoo*(Py - a_2*sin(th_1) - a_3*sin(th_1 + th_2))
finish set_solved th_2
basenode:  Completion Detect  ticked





           Completion Detector:  6  variables,  2  are solved.
             solved:  th_1 (sinANDcos);   th_2 (algebra);



basenode:  Completion Detect  FAIL
variable on blackboard: th_3



set_solved:  th_3       by:  algebra
             th_3 = r_21*th_3/sin(th_1 + th_2 + th_3)


 -  - - - -
[th_1, th_2, th_3, th_123, th_12, th_23]
Trying to find:  th_3
 - - - - -
r_21*th_3/sin(th_1 + th_2 + th_3)
```

**Comment by blake5634** [comment]
We've reproduced your problem.   I have added tests to algebra_solver to expose this issue.   When algebra solver solves a sum of angles eqn like

       th_123 = th_1 + th_2 + th_3
       
then set_solved seems to go into an infinite loop in the solution tree search. 
@dianmuz ???

**Comment by blake5634** [comment]
This is another example of same bug from @nithinpachday
BH

if(name == 'Luci'):
# standardize on the order "alpha N-1, a N-1, d N, theta N' for the DH table columns.

    dh = sp.Matrix([
        [sp.pi/2 , 	 0.,         d_1,        th_1],
        [0       , 	 a_1,         0.,         th_2],
        [0       , 	 a_2,         0.,         th_3],
        [-sp.pi/2,   a_3,         0.,         th_4],
        [0       ,	 a_4,         0.,         th_5],
        [0       ,	  0,          0,            0]
        ])
        
    vv = [1, 1, 1, 1, 1, 0]
    variables = [unknown(th_1), unknown(th_2), unknown(th_3), unknown(th_4), unknown(th_5)]
    params = [d_1, a_1, a_2, a_3, a_4]
    pvals = {d_1: 0.05, a_1: 0.247, a_2: 0.177, a_3:.085, a_4: 0.}

**Comment by blake5634** [comment]
Arm_3 now works with latest master branch.    I'm closing this and opening another issue for  Luci  (which is stuck in "detect_parent" of set_solved.
