### ISSUE TITLE
Error in Python CodeGen: global name 'acos' is not defined

### ISSUE THREAD

**Issue by xoxota99** [uw-biorobotics/IKBT#20]
If the set of solution methods contains the arccos or arcsin methods, the correct imports are not generated into the resulting python code, resulting in the below errors:
- global name 'acos' is not defined
- global name 'asin' is not defined

**Comment by blake5634** [comment]
I think I recall that bug, just do    acos--> np.acos      asin---> np.asin
I'll keep issue open -- it's an easy fix.  (but also easy to fix in your generated code   ;)   )

**Comment by xoxota99** [comment]
Yep, super easy fix. Can also just 'from math import acos'

**Comment by xoxota99** [comment]
@blake5634 is there a support forum for IKBT, or a better place for me to ask general-knowledge questions about the project, besides the Github issues queue?

**Comment by blake5634** [comment]
There is not yet a support forum.   I don't mind using the github issues for now but what do you think would be the best platform for the newbie questions, feature requests, etc???

**Comment by xoxota99** [comment]
Github issues works great, I just have a lot of newbie questions, and don't want to clog up the wrong inbox :-)

**Comment by xoxota99** [comment]
Fixed in https://github.com/uw-biorobotics/IKBT/commit/e1517a553acc8687dda01d5da5dacf8f29c9fe3f . Closing.
