### ISSUE TITLE
Computation won't finish

### ISSUE THREAD

**Issue by MarcGondran** [uw-biorobotics/IKBT#27]
Hi,

Thank you for your work, I really appreciate it.

Unfortunatelly, I experience issues while computing the Inverse Kinematics solver. I tried several robot which worked well as the Wrist but for the Khat6DOF, the computation stays stuck. It seems to stop computing here :

`
set_solved:  th_23       by:  simultaneous eqn
             th_23 = atan2((-Pz + l_1)*(-a_2*cos(th_3) - a_3) - (a_2*sin(th_3) + l_4)*(-Px*cos(th_1) - Py*sin(th_1) + a_1*cos(th_1)), (-Pz + l_1)*(a_2*sin(th_3) + l_4) + (-a_2*cos(th_3) - a_3)*(-Px*cos(th_1) - Py*sin(th_1) + a_1*cos(th_1)))

atan2((-Pz + l_1)*(-a_2*cos(th_3) - a_3) - (a_2*sin(th_3) + l_4)*(-Px*cos(th_1) - Py*sin(th_1) + a_1*cos(th_1)), (-Pz + l_1)*(a_2*sin(th_3) + l_4) + (-a_2*cos(th_3) - a_3)*(-Px*cos(th_1) - Py*sin(th_1) + a_1*cos(th_1)))
`
It's still consuming about 10% of my CPU but it stayed so overnight. Do you know about it ?

Thank you.

Marc

**Comment by blake5634** [comment]
Yes - this is same as issue #18.   I'm closing this one and refering you to #18.   Sorry still working on that though.
