### ISSUE TITLE
Python 3.x support?

### ISSUE THREAD

**Issue by bfouts-kindred** [uw-biorobotics/IKBT#29]
Python 2.7 is being deprecated. Do you plan to migrate to 3.x any time soon?

**Comment by blake5634** [comment]
No immediate bandwidth for that.   Any volunteers out there?   If sympy is migrated then it should be just a matter of print x --> print(x) (for which there are automated tools).

**Comment by gonzalocasas** [comment]
`sympy 1.6` is already migrated to 3.x
