### ISSUE TITLE
[NewRobot]For ABB CRB collaborative robots, is there an analytical inverse solution?

### ISSUE THREAD

**Issue by WangZP10969** [uw-biorobotics/IKBT#40]
I learned about your project from the blog. This is a very meaningful project. I tried the sample code and the output is very explanatory.
I am manually sorting out the analytical inverse kinematics recently. For the ABB CRB 15000  robot, it seems that no analytical inverse solution can be found. Did you use your script to get the solution? Does the robot have no analytical inverse solution?
https://new.abb.com/products/robotics/en/cobot/crb-15000
I used a modified DH model, I am not sure if you use this model
![image](https://user-images.githubusercontent.com/47802547/136593003-d665283d-82b2-4642-995f-8ee3dfc5329b.png)
![image](https://user-images.githubusercontent.com/47802547/136593506-5ff1ad4a-2245-48cf-b94b-b0dc7e11a5e7.png)
![image](https://user-images.githubusercontent.com/47802547/136593179-9a483347-cd59-4fac-a5fc-8327adbdcf34.png)

Thank you very much for your contribution!

**Comment by blake5634** [comment]
Thank you for complimenting the project!  We appreciate the feedback.  

  If IKBT cannot find a solution, there are two possibilities, 1) The robot has no solution   2) There is a solution but IKBT cannot find it.     Unfortunately, as far as I know, there is no way to prove that a robot arm has no closed form solution.    Although there is a necessary condition for solution (Piper and Roth: three intersecting axis), AFAIK there is no sufficient condition.        Regarding point 2, we do not make the claim that IKBT can solve all solvable robots.   Not sure how to test that claim actually.   

Sorry, I do not have time to check your DH parameters.    

BH
