### ISSUE TITLE
Cannot solve my 6DoF robot case

### ISSUE THREAD

**Issue by peng-zhihui** [uw-biorobotics/IKBT#47]
Hello, great project first! however when I try to test the code with my [Dummy Robot](https://github.com/peng-zhihui/Dummy-Robot), I cannot get the correct result, and here are my DH parameters：
```
    if (name == 'Dummy'):
        dh = sp.Matrix([
            [-sp.pi / 2, 0.035, 0.109, th_1],
            [0, 0.146, 0, (th_2 - sp.pi / 2)],
            [sp.pi / 2, 0, 0.052, (th_3 + sp.pi / 2)],
            [-sp.pi / 2, 0, 0.115, th_4],
            [sp.pi / 2, 0, 0, th_5],
            [0, 0, 0.072, th_6]   
        ])
        vv = [1, 1, 1, 1, 1, 1]

        variables = [unknown(th_1), unknown(th_2), unknown(th_3), unknown(th_4), unknown(th_5), unknown(th_6)]
        params = []
        pvals = {}  # meters
```

which represent for:
![](https://pengzhihui-markdown.oss-cn-shanghai.aliyuncs.com/img/20221025204214.PNG)

It takes too long to come up with result output, any suggestion please?

**Comment by blake5634** [comment]
I'm not sure but don't forget  1) use MODIFIED DH parameters (Craig notation) and 2) Not all 6DOF robots even HAVE a solution.   If you try to solve a non-solvable chain, it will just loop for a long time.     Maybe check your last axis.   It seems to be parallel to axis 5.

**Comment by peng-zhihui** [comment]
Thanks for your reply!
It's strange that in fact I have solved this Robot IK manually before, and it works just fine in both simulation & real machine, this arm config should be a quite normal one, it looks like this:
![image](https://user-images.githubusercontent.com/12994887/197835182-f093d64e-13ac-4a71-975a-481cab9b24f3.png)

so 1) I'm pretty sure I used MDH parameters；2) I'm also sure it must have a usable solution (since it's already worked in my robot firmware)

I have tried some cases: 
1) If I use the theta variable with home offset (like `(th_2 - sp.pi / 2)`), then the ik solver may stuck in endless loop.
2) If I use the theta variable without home offset , I can get a result, but the test result of the generated python code is way from correct.

The idea of solving IK problem by imitating the behavior of human experts is brilliant for me, really wish I could use it in my next humanoid robot design! Wondering if there's anything I can modify to make it right?

**Comment by blake5634** [comment]
Thanks for your thoughtful response. 
I never set up the IK problem with joint offsets and so I do not have it in my test cases.  It's interesting that the method can't solve with offsets.   Your solution by step 2 above is fully valid.   The robot is simply in a different pose when th_2=0.    This may cause problem with the Python output.   And nice robot build BTW.
The referenced paper in README.md explains the algorithm in detail.    The easiest thing is to change the high level logic by modification of the behavior tree.   The BT is fully contained in ikSolver.py.    Good luck!

**Comment by peng-zhihui** [comment]
Appreciate for your given information, I'll try to do some debug later, wish I can make it work :D
